import { Inter } from 'next/font/google'
import './globals.css'
import { AuthProvider } from './components/authContext/user';

const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Gestão SENAI',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="icon" href="over.png" type="image/png" />
      </head>
      <body className={inter.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}